---
AWSTemplateFormatVersion: 2010-09-09

Description: Deployment configurations for projectchurchifyfrontend

# Parameters are like the environment variables
Parameters:
  FirebaseApiKey:
    NoEcho: "true"
    Description: The app apikey for firebase
    Type: String
  FirebaseAuthDomain:
    NoEcho: "true"
    Description: The app authDomain for firebase
    Type: String
  FirebaseDatabaseURL:
    NoEcho: "true"
    Description: The app databaseUrl for firebase
    Type: String
  FirebaseProjectId:
    NoEcho: "true"
    Description: The app projectId for firebase
    Type: String
  FirebaseStorageBucket:
    NoEcho: "true"
    Description: The app storageBucket for firebase
    Type: String
  FirebaseMessagingSenderId:
    NoEcho: "true"
    Description: The app messagingSenderId for firebase
    Type: String
  FirebaseAppId:
    NoEcho: "true"
    Description: The app appId for firebase
    Type: String
  BaseURL:
    NoEcho: "true"
    Description: The app baseURL for AWS projectchurchify apis on EB
    Type: String
 
  GitSourceRepo:
    Type: String
    Description: GitHub source repository
    Default: churchify-app-frontend
    MinLength: 1
    MaxLength: 100
    ConstraintDescription: GitHub repository name

  GitBranch:
    Type: String
    Default: develop
    Description: GitHub git repository branch - change triggers a new build
    MinLength: 1
    MaxLength: 100
    ConstraintDescription: GitHub repository branch name is required

  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub API or personal access token - see https://github.com/blog/1509-personal-api-tokens
    MinLength: 3
    MaxLength: 100
    ConstraintDescription: GitHub personal access token is required

  GitHubUser:
    Type: String
    Default: GerrardE
    Description: GitHub username or organization
    MinLength: 3
    MaxLength: 100
    ConstraintDescription: GitHub username or organization is required

  OperatorEmail:
    Description: Email address to notify if there are any operational issues
    Type: String
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: must be a valid email address.

# Resources include all aws services required to run the project
Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"

  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: projectchurchify
      Repository: !Ref GitSourceRepo
      Description: Frontend application for projectchurchify
      OauthToken: !Ref GitHubToken
      EnvironmentVariables:
        - Name: apiKey
          Value: !Ref FirebaseApiKey
        - Name: authDomain
          Value: !Ref FirebaseAuthDomain
        - Name: databaseURL
          Value: !Ref FirebaseDatabaseURL
        - Name: projectId
          Value: !Ref FirebaseProjectId
        - Name: storageBucket
          Value: !Ref FirebaseStorageBucket
        - Name: messagingSenderId
          Value: !Ref FirebaseMessagingSenderId
        - Name: appId
          Value: !Ref FirebaseAppId
        - Name: baseURL
          Value: !Ref BaseURL
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: dist/
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      CustomRules:
        - Source: /dist/index.html
          Target: /index.html
          Status: '200'
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: develop
      AppId: !GetAtt AmplifyApp.AppId
      Description: Develop Branch
      EnableAutoBuild: true
      Tags:
        - Key: Name
          Value: projectchurchify
        - Key: Branch
          Value: develop

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Ref: OperatorEmail
          Protocol: email

Outputs:
  StackName:
    Description: "Stack name"
    Value: !Sub "${AWS::StackName}"

  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain
